name: CI
env:
  CI: true

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        node: ['10.x', '12.x']
        os: [ubuntu-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - run: npm install

      - run: npm run lint
      - run: npm run build
      - run: npm test
